export interface SolutionFeature {
  title: string
  description: string
}

export interface SolutionData {
  slug: string[]
  title: string
  subtitle: string
  description: string
  badge: string
  features: SolutionFeature[]
  useCases: string[]
  cta: string
  ctaHref: string
}

export const solutionsData: SolutionData[] = [
  // Use Cases
  {
    slug: ['rag'],
    title: 'RAG Applications',
    subtitle: 'Build retrieval-augmented generation at enterprise scale',
    description: 'Ground every LLM response in your proprietary data. Hanzo\'s vector database, embedding pipeline, and inference gateway let you build production RAG in hours — not months.',
    badge: 'Use Case',
    features: [
      { title: 'Managed Vector Store', description: 'pgvector on Hanzo Base — no separate infrastructure. Index billions of embeddings with sub-10ms retrieval.' },
      { title: 'Embedding Pipeline', description: 'Auto-embed documents on ingest. Supports Zen3-embedding, OpenAI, Cohere, and custom models.' },
      { title: 'Hybrid Search', description: 'Combine dense vector search with BM25 keyword search for best-of-both precision.' },
      { title: 'Context Window Management', description: 'Smart chunking, re-ranking, and context compression to fit retrieved knowledge into any model.' },
      { title: 'Observability', description: 'Trace every retrieval step. Debug hallucinations by inspecting exactly what context was injected.' },
      { title: 'Multi-tenant Isolation', description: 'Namespace indexes per customer. Keep enterprise data siloed with row-level security.' },
    ],
    useCases: [
      'Internal knowledge bases and enterprise search',
      'Customer support with grounded, accurate answers',
      'Legal and compliance document analysis',
      'Medical and scientific literature review',
      'Code repository search and assistant',
    ],
    cta: 'Start building',
    ctaHref: 'https://docs.hanzo.ai/guides/rag',
  },
  {
    slug: ['agents'],
    title: 'AI Agents',
    subtitle: 'Deploy autonomous agents that get work done',
    description: 'Give your AI access to tools, memory, and the ability to plan multi-step tasks. Hanzo provides the infrastructure — you focus on the agent logic.',
    badge: 'Use Case',
    features: [
      { title: 'Tool Use & Function Calling', description: 'Connect agents to any API, database, or service with standardized MCP tools. 260+ pre-built integrations.' },
      { title: 'Persistent Memory', description: 'Agents remember context across sessions. Vector memory, structured state, and episodic recall — all managed.' },
      { title: 'Multi-Agent Orchestration', description: 'Route tasks between specialized agents. Build supervisor-worker hierarchies that scale with complexity.' },
      { title: 'Human-in-the-Loop', description: 'Gate high-stakes actions behind approval flows. Maintain control while maximizing autonomy.' },
      { title: 'Sandboxed Execution', description: 'Run agent-generated code in isolated containers. Full OS access without risk to production systems.' },
      { title: 'Streaming & Observability', description: 'Real-time thought streams, tool call traces, and token-level cost attribution per agent run.' },
    ],
    useCases: [
      'Automated research and competitive intelligence',
      'Data pipeline orchestration and ETL',
      'Customer onboarding and lifecycle automation',
      'Code review and PR automation',
      'Complex enterprise workflow automation',
    ],
    cta: 'Explore agent SDK',
    ctaHref: 'https://docs.hanzo.ai/guides/agents',
  },
  {
    slug: ['realtime'],
    title: 'Real-time AI',
    subtitle: 'Stream AI responses with sub-100ms latency',
    description: 'Deliver instant, fluid AI experiences. Hanzo\'s streaming infrastructure handles millions of concurrent streams — from chat to live audio to real-time analytics.',
    badge: 'Use Case',
    features: [
      { title: 'SSE & WebSocket Streaming', description: 'Native support for Server-Sent Events and WebSockets. Tokens arrive as they\'re generated — no buffering.' },
      { title: 'Edge Inference', description: 'Route requests to the nearest inference node. Sub-100ms first-token latency for users worldwide.' },
      { title: 'Real-time Voice', description: 'Bidirectional audio streaming with Zen Live. Interrupt handling, turn detection, and <300ms response.' },
      { title: 'Live Data Integration', description: 'Stream live data into context — market feeds, IoT sensors, database CDC — without batching delays.' },
      { title: 'Backpressure Handling', description: 'Intelligent rate limiting and queue management. Never drop a stream under load.' },
      { title: 'Multiplexed Connections', description: 'One persistent connection, many concurrent streams. Efficient for high-frequency, high-volume workloads.' },
    ],
    useCases: [
      'Live customer chat with instant AI responses',
      'Real-time voice assistants and IVR systems',
      'Live document generation and editing co-pilot',
      'Financial market analysis and alerting',
      'Real-time moderation at scale',
    ],
    cta: 'View streaming docs',
    ctaHref: 'https://docs.hanzo.ai/guides/streaming',
  },
  {
    slug: ['fine-tuning'],
    title: 'Fine-tuning',
    subtitle: 'Train models that know your domain inside out',
    description: 'Adapt frontier models to your specific vocabulary, tone, and tasks. Hanzo\'s fine-tuning pipeline handles data prep, distributed training, and deployment — all on your infrastructure.',
    badge: 'Use Case',
    features: [
      { title: 'Supervised Fine-tuning (SFT)', description: 'Full fine-tuning and LoRA/QLoRA adapters. Train on instruction-response pairs with your own data.' },
      { title: 'RLHF & DPO', description: 'Align models to human preferences with reinforcement learning or direct preference optimization.' },
      { title: 'Data Flywheel', description: 'Capture production traffic, curate high-quality examples, and continuously improve your models.' },
      { title: 'On-premise Training', description: 'Train on your GPUs — NVIDIA H100, A100, or L40S. Data never leaves your VPC.' },
      { title: 'Evaluation Suite', description: 'Automated evals against domain benchmarks before every deployment. Catch regression before it ships.' },
      { title: 'Adapter Management', description: 'Version, tag, and serve multiple LoRA adapters on a single base model. Switch at inference time.' },
    ],
    useCases: [
      'Domain-specific language models (legal, medical, finance)',
      'Brand voice and tone alignment',
      'Code generation for proprietary frameworks',
      'Customer service with company-specific knowledge',
      'Multilingual localization and translation',
    ],
    cta: 'Start fine-tuning',
    ctaHref: 'https://docs.hanzo.ai/guides/fine-tuning',
  },
  {
    slug: ['vision'],
    title: 'Computer Vision',
    subtitle: 'Process images and video at production scale',
    description: 'Extract structured data from any visual input. Hanzo\'s vision pipeline handles ingestion, processing, and structured output — from single images to high-volume video streams.',
    badge: 'Use Case',
    features: [
      { title: 'Multimodal Models', description: 'Zen VL and Zen Omni for image understanding, OCR, document parsing, and visual Q&A.' },
      { title: 'Video Processing', description: 'Frame extraction, scene detection, and temporal analysis for long-form video content.' },
      { title: 'Structured Extraction', description: 'Convert visual content to JSON, tables, or any schema. Works on receipts, forms, diagrams, charts.' },
      { title: 'Real-time Detection', description: 'Object detection, face recognition, and anomaly detection on live camera feeds.' },
      { title: 'Image Generation', description: 'Zen Artist for photorealistic image generation and editing. Zen Artist Edit for precise inpainting.' },
      { title: 'Vision Embeddings', description: 'Embed images in the same space as text for multimodal search and clustering.' },
    ],
    useCases: [
      'Document digitization and intelligent OCR',
      'Product catalog automation from photos',
      'Quality control and defect detection',
      'Medical imaging analysis',
      'Security and surveillance monitoring',
    ],
    cta: 'Explore vision models',
    ctaHref: '/models',
  },
  {
    slug: ['audio'],
    title: 'Voice & Audio',
    subtitle: 'Speech recognition and synthesis at any scale',
    description: 'Build voice-first experiences with state-of-the-art ASR, TTS, and real-time audio streaming. Hanzo\'s audio stack supports 50+ languages with human-level accuracy.',
    badge: 'Use Case',
    features: [
      { title: 'Speech Recognition (ASR)', description: 'Zen Scribe for transcription — streaming and batch. 50+ languages, speaker diarization, punctuation.' },
      { title: 'Text-to-Speech (TTS)', description: 'Zen Dub for natural voice synthesis. 30+ voices, custom cloning, SSML control.' },
      { title: 'Real-time Voice AI', description: 'Zen Live for bidirectional voice conversations. <300ms round-trip with interrupt handling.' },
      { title: 'Audio Translation', description: 'Zen Translator for speech-to-speech translation across languages in real time.' },
      { title: 'Speaker Identification', description: 'Diarize multi-speaker recordings. Track who said what, when.' },
      { title: 'Audio Embeddings', description: 'Embed audio for search, clustering, and cross-modal retrieval.' },
    ],
    useCases: [
      'Voice assistants and IVR automation',
      'Meeting transcription and intelligence',
      'Podcast and media accessibility',
      'Multilingual customer support',
      'Audio content moderation',
    ],
    cta: 'Explore audio models',
    ctaHref: '/models',
  },
  // Stacks
  {
    slug: ['stacks'],
    title: 'Hanzo Stacks',
    subtitle: 'Production-ready AI application templates',
    description: 'Launch complete AI applications in days, not months. Each Hanzo Stack is a battle-tested template combining the right models, infrastructure, and integrations for your use case.',
    badge: 'Stacks',
    features: [
      { title: 'SaaS Starter', description: 'Auth, billing, database, and AI — production-ready from day one. Ship your AI SaaS faster.' },
      { title: 'Analytics Stack', description: 'Self-hosted product analytics with AI insights. Replace Mixpanel and Amplitude with a system you own.' },
      { title: 'E-commerce Stack', description: 'AI-powered storefront with personalization, recommendations, and conversational shopping.' },
      { title: 'Developer Portal', description: 'Full API documentation, SDK generation, and developer onboarding — powered by your own AI.' },
      { title: 'One-click Deploy', description: 'Every stack deploys to Hanzo Cloud, your own Kubernetes cluster, or any cloud provider.' },
      { title: 'Fully Customizable', description: 'Stacks are starting points, not constraints. Fork and extend with your own components.' },
    ],
    useCases: [
      'Launch AI SaaS products rapidly',
      'Modernize legacy applications with AI',
      'Build internal tools for enterprise teams',
      'Create developer-facing API products',
      'Deploy self-hosted alternatives to SaaS tools',
    ],
    cta: 'Browse all stacks',
    ctaHref: '/solutions/stacks/saas',
  },
  {
    slug: ['stacks', 'saas'],
    title: 'SaaS Starter Stack',
    subtitle: 'Launch your AI SaaS in days, not months',
    description: 'Everything you need for a production AI SaaS: auth, billing, database, AI gateway, and a polished UI — all pre-integrated and ready to customize.',
    badge: 'Stack',
    features: [
      { title: 'Authentication', description: 'SSO, MFA, social login via Hanzo Identity. Enterprise SAML and SCIM provisioning included.' },
      { title: 'Billing & Metering', description: 'Stripe integration with usage-based metering. Credit systems, seat pricing, and enterprise contracts.' },
      { title: 'AI Gateway', description: 'Route to 100+ models through one API. Cost controls, rate limiting, and per-tenant quotas.' },
      { title: 'Realtime Database', description: 'Hanzo Base for auth, database, storage, and realtime — one backend, zero ops.' },
      { title: 'Admin Dashboard', description: 'User management, usage analytics, and billing overview. White-label ready.' },
      { title: 'Marketing Site', description: 'Landing page, pricing page, and blog — all built in and ready to customize.' },
    ],
    useCases: ['B2B AI SaaS startups', 'Internal AI tools', 'API-first products', 'Enterprise AI platforms'],
    cta: 'Get the template',
    ctaHref: 'https://github.com/hanzoai',
  },
  {
    slug: ['stacks', 'analytics'],
    title: 'Analytics Stack',
    subtitle: 'Self-hosted product analytics with AI insights',
    description: 'Replace Mixpanel, Amplitude, or Heap with a system you own. Hanzo Analytics gives you full control over your data with AI-powered insights and no vendor lock-in.',
    badge: 'Stack',
    features: [
      { title: 'Event Tracking', description: 'Capture any user action with a single line of code. Auto-capture for clicks, forms, and page views.' },
      { title: 'AI Insight Engine', description: 'Ask questions about your users in plain English. Get answers in seconds, not dashboards.' },
      { title: 'Funnel & Retention', description: 'Conversion funnels, cohort retention, and path analysis — all self-hosted.' },
      { title: 'Feature Flags', description: 'Roll out features to segments. A/B test with statistical significance built in.' },
      { title: 'Session Replay', description: 'Watch exactly how users interact with your product. Debug UX issues fast.' },
      { title: 'Data Ownership', description: 'All data in your own PostgreSQL. Export anytime. No data sharing with third parties.' },
    ],
    useCases: ['SaaS product analytics', 'GDPR/CCPA compliance', 'Enterprise internal analytics', 'Privacy-first products'],
    cta: 'Deploy analytics',
    ctaHref: 'https://insights-app.hanzo.ai',
  },
  {
    slug: ['stacks', 'ecommerce'],
    title: 'E-commerce Stack',
    subtitle: 'AI-powered storefront with personalization at scale',
    description: 'Build an e-commerce experience that learns from every interaction. AI-driven product discovery, personalized recommendations, and conversational commerce — all in one stack.',
    badge: 'Stack',
    features: [
      { title: 'AI Search & Discovery', description: 'Semantic product search that understands intent. Zero-result fallbacks, typo tolerance, faceted filtering.' },
      { title: 'Personalization Engine', description: 'Real-time recommendations based on browsing history, purchase patterns, and similar users.' },
      { title: 'Conversational Shopping', description: 'Chat-based shopping assistant that knows your entire catalog and can complete purchases.' },
      { title: 'Dynamic Pricing', description: 'AI-driven pricing optimization based on demand, inventory, and competitive signals.' },
      { title: 'Visual Search', description: 'Let customers search by uploading photos. Find exact or similar products instantly.' },
      { title: 'Fraud Detection', description: 'ML-based fraud scoring on every transaction. Reduce chargebacks without blocking good customers.' },
    ],
    useCases: ['D2C brands', 'Marketplace platforms', 'B2B procurement portals', 'Luxury and fashion retail'],
    cta: 'Build your storefront',
    ctaHref: '/contact/sales',
  },
  {
    slug: ['stacks', 'devportal'],
    title: 'Developer Portal Stack',
    subtitle: 'The API documentation and onboarding platform your developers deserve',
    description: 'Give developers an exceptional experience from day one. API reference, guides, sandbox environment, and AI assistant — all in a polished, branded developer portal.',
    badge: 'Stack',
    features: [
      { title: 'AI Documentation Assistant', description: 'Developers ask questions in natural language and get instant, accurate answers from your docs.' },
      { title: 'Interactive API Explorer', description: 'Test any endpoint directly in the browser with your own credentials. OpenAPI 3.x rendering.' },
      { title: 'SDK Generation', description: 'Auto-generate SDKs in TypeScript, Python, Go, Rust, and Java from your OpenAPI spec.' },
      { title: 'Sandbox Environment', description: 'Isolated sandbox with mock data and test credentials. Onboard developers without risk.' },
      { title: 'Changelog & Versioning', description: 'Structured changelog with diff views. Support multiple API versions side by side.' },
      { title: 'Analytics', description: 'Track which docs pages developers visit, where they get stuck, and what they search for.' },
    ],
    useCases: ['API-first companies', 'Platform businesses', 'Enterprise software vendors', 'Developer tools startups'],
    cta: 'Build your dev portal',
    ctaHref: '/contact/sales',
  },
  // Industries
  {
    slug: ['industries', 'healthcare'],
    title: 'Healthcare AI',
    subtitle: 'HIPAA-compliant AI infrastructure for healthcare organizations',
    description: 'Accelerate care delivery with AI that meets the highest standards of security, compliance, and accuracy. Built for EHR integration, clinical workflows, and patient engagement.',
    badge: 'Industry',
    features: [
      { title: 'HIPAA Compliance', description: 'End-to-end encryption, audit logs, and BAAs available. Data never leaves your designated region.' },
      { title: 'Clinical NLP', description: 'Extract structured data from clinical notes, discharge summaries, and lab reports with medical-grade accuracy.' },
      { title: 'EHR Integration', description: 'Native FHIR R4 support. Connect to Epic, Cerner, and all major EHR systems.' },
      { title: 'Medical Imaging', description: 'AI-assisted radiology, pathology, and dermatology. Flag findings for clinician review.' },
      { title: 'Patient Engagement', description: 'AI triage, appointment scheduling, and care plan adherence — in any language.' },
      { title: 'Clinical Decision Support', description: 'Evidence-based recommendations grounded in clinical literature. Always cites its sources.' },
    ],
    useCases: ['Hospital systems and IDNs', 'Digital health startups', 'Pharmaceutical companies', 'Medical device companies', 'Health insurance and payers'],
    cta: 'Talk to our healthcare team',
    ctaHref: '/contact/sales',
  },
  {
    slug: ['industries', 'finance'],
    title: 'Financial Services AI',
    subtitle: 'Enterprise-grade AI for regulated financial institutions',
    description: 'Deploy AI across trading, risk, compliance, and customer service with the security controls and explainability that financial regulators require.',
    badge: 'Industry',
    features: [
      { title: 'SOC 2 Type II', description: 'Certified infrastructure with continuous compliance monitoring. Audit reports available on request.' },
      { title: 'Explainable AI', description: 'Every model decision includes a full reasoning trace. Meet model risk management requirements.' },
      { title: 'Market Data Integration', description: 'Real-time streaming of market data into AI context. Sub-millisecond latency on trading signals.' },
      { title: 'Fraud & AML', description: 'Graph-based fraud detection and AML transaction monitoring with adaptive ML models.' },
      { title: 'Document Intelligence', description: 'Extract structured data from regulatory filings, loan applications, and financial statements.' },
      { title: 'Private Cloud Deployment', description: 'On-premise or dedicated cloud. Complete network isolation for the most sensitive workloads.' },
    ],
    useCases: ['Investment banks and asset managers', 'Insurance companies', 'Fintech and neobanks', 'Payment processors', 'Regulatory compliance teams'],
    cta: 'Talk to our finance team',
    ctaHref: '/contact/sales',
  },
  {
    slug: ['industries', 'retail'],
    title: 'Retail & E-commerce AI',
    subtitle: 'AI that drives revenue at every stage of the customer journey',
    description: 'From discovery to post-purchase, Hanzo\'s retail AI stack personalizes every touchpoint, optimizes operations, and reduces costs across your entire retail business.',
    badge: 'Industry',
    features: [
      { title: 'Personalization at Scale', description: 'Real-time recommendations for every shopper, across every channel — web, app, email, and in-store.' },
      { title: 'Inventory Intelligence', description: 'Demand forecasting, stockout prediction, and automated replenishment. Reduce overstock and lost sales.' },
      { title: 'Conversational Commerce', description: 'AI shopping assistants that understand natural language, know your catalog, and convert.' },
      { title: 'Price Optimization', description: 'Dynamic pricing with competitor monitoring, elasticity modeling, and margin guardrails.' },
      { title: 'Visual Merchandising', description: 'AI-generated product descriptions, lifestyle imagery, and size/fit recommendations.' },
      { title: 'Supply Chain Visibility', description: 'Predict and mitigate supply chain disruptions before they impact the customer.' },
    ],
    useCases: ['D2C and omnichannel brands', 'Grocery and convenience retail', 'Luxury and fashion', 'Marketplace operators', 'B2B distributors'],
    cta: 'Talk to our retail team',
    ctaHref: '/contact/sales',
  },
  {
    slug: ['industries', 'enterprise'],
    title: 'Enterprise AI',
    subtitle: 'Private cloud AI deployment for the world\'s most demanding organizations',
    description: 'Deploy Hanzo entirely within your infrastructure. No data egress, no shared tenancy, complete control — with the same capability as our public cloud, running on your terms.',
    badge: 'Enterprise',
    features: [
      { title: 'Air-gapped Deployment', description: 'Run fully offline with no internet connectivity required. Ideal for classified and sensitive environments.' },
      { title: 'VPC & On-premise', description: 'Deploy on AWS, Azure, GCP, or your own data center. Full Terraform and Helm chart support.' },
      { title: 'Enterprise SSO', description: 'SAML 2.0, OIDC, and Active Directory integration. SCIM provisioning for automated user management.' },
      { title: 'Role-based Access Control', description: 'Fine-grained RBAC at the model, endpoint, and data level. Full audit trail for every request.' },
      { title: 'SLA Guarantees', description: '99.99% uptime SLA with dedicated support engineers. P0 response in under 15 minutes.' },
      { title: 'Custom Model Training', description: 'Train and fine-tune models on your proprietary data without it ever leaving your environment.' },
    ],
    useCases: ['Fortune 500 enterprises', 'Government and defense', 'Critical infrastructure', 'Financial institutions', 'Healthcare systems'],
    cta: 'Contact enterprise sales',
    ctaHref: '/contact/sales',
  },
]

export function getSolutionBySlug(slug: string[]): SolutionData | undefined {
  return solutionsData.find(
    s => s.slug.length === slug.length && s.slug.every((part, i) => part === slug[i])
  )
}
